use serde::Deserialize;
use crate::commands::maintenance::sha256_hex;
const MAX_FIELD:usize=128;
#[derive(Debug,Clone,PartialEq,Eq)] pub struct TargetRevision(String);
impl TargetRevision { pub fn parse(v:&str)->Result<Self,PrepareContractError>{if (v.len()==40||v.len()==64)&&v.bytes().all(|b|b.is_ascii_hexdigit()&&!b.is_ascii_uppercase()){Ok(Self(v.into()))}else{Err(PrepareContractError::InvalidTarget)}} pub fn as_str(&self)->&str{&self.0} }
#[derive(Debug,Clone,PartialEq,Eq)] pub struct DeploymentFingerprint(pub String);
#[derive(Debug,Clone,PartialEq,Eq)] pub struct PreparedPlan { pub current_revision:TargetRevision,pub target_revision:TargetRevision,pub change_count:u32 }
#[derive(Debug,Clone,Copy,PartialEq,Eq)] pub enum PrepareContractError { Malformed, UnsupportedVersion, InvalidTarget }
#[derive(Deserialize)] #[serde(deny_unknown_fields,rename_all="camelCase")] struct Wire { protocol_version:u32,status:String,current_revision:String,target_revision:String,change_count:u32 }
pub fn parse_prepare(raw:&str)->Result<PreparedPlan,PrepareContractError>{if raw.len()>32*1024{return Err(PrepareContractError::Malformed)}let w:Wire=serde_json::from_str(raw).map_err(|_|PrepareContractError::Malformed)?;if w.protocol_version!=1{return Err(PrepareContractError::UnsupportedVersion)}if w.status!="ready"||w.current_revision.len()>MAX_FIELD||w.target_revision.len()>MAX_FIELD{return Err(PrepareContractError::Malformed)}Ok(PreparedPlan{current_revision:TargetRevision::parse(&w.current_revision)?,target_revision:TargetRevision::parse(&w.target_revision)?,change_count:w.change_count})}
pub fn fingerprint(workload:&str,revision:u32,digest:&str,target:&TargetRevision,verification:&[String])->DeploymentFingerprint{let mut v=verification.to_vec();v.sort();let s=format!("v1\x1f{}\x1f{}\x1f{}\x1f{}\x1f{}",workload,revision,digest,target.as_str(),v.join("\x1e"));DeploymentFingerprint(sha256_hex(s.as_bytes()))}
#[cfg(test)] mod tests { use super::*; fn j(t:&str)->String{format!(r#"{{"protocolVersion":1,"status":"ready","currentRevision":"{}","targetRevision":"{}","changeCount":1}}"#,"a".repeat(40),t)} #[test] fn parser_and_revision_are_strict(){assert!(parse_prepare(&j(&"b".repeat(40))).is_ok());for x in ["main","../x","a b",&"a".repeat(65)]{assert!(TargetRevision::parse(x).is_err())}assert!(parse_prepare("{}").is_err());assert!(parse_prepare(r#"{"protocolVersion":2}"#).is_err());} #[test] fn fingerprint_changes_only_with_evidence(){let t=TargetRevision::parse(&"a".repeat(40)).unwrap();let a=fingerprint("w",1,&"b".repeat(64),&t,&["svc".into()]);assert_eq!(a,fingerprint("w",1,&"b".repeat(64),&t,&["svc".into()]));assert_ne!(a,fingerprint("w",2,&"b".repeat(64),&t,&["svc".into()]));assert_ne!(a,fingerprint("w",1,&"c".repeat(64),&t,&["svc".into()]));assert_ne!(a,fingerprint("w",1,&"b".repeat(64),&t,&["x".into()]));} }
