import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { acknowledgeAlert, getAlerts } from "@/lib/tauri/monitoring";
import type { Alert, AlertSeverity } from "@/types/alert";

const severities: AlertSeverity[] = ["critical", "warning", "info"];
function label(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (char: string) => char.toUpperCase()); }

export function AlertCenterScreen() {
  const [alerts, setAlerts] = useState<Alert[] | null>(null); const [state, setState] = useState<string>("open"); const [severity, setSeverity] = useState<string>("all"); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => getAlerts().then(setAlerts).catch(() => setError("Could not load alerts.")), []);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => (alerts ?? []).filter((alert) => (state === "open" ? alert.state !== "resolved" : state === "all" || alert.state === state) && (severity === "all" || alert.severity === severity)), [alerts, severity, state]);
  async function acknowledge(id: string) { try { await acknowledgeAlert(id); await load(); } catch { setError("Could not acknowledge alert."); } }
  return <div className="flex flex-col gap-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">Alerts</h1><p className="mt-0.5 text-sm text-muted-foreground">Persistent conditions that require attention.</p></div><div className="flex gap-2"><Select value={state} onValueChange={setState}><SelectTrigger aria-label="Filter alert state"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open">Unresolved</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="acknowledged">Acknowledged</SelectItem><SelectItem value="resolved">Resolved</SelectItem><SelectItem value="all">All states</SelectItem></SelectContent></Select><Select value={severity} onValueChange={setSeverity}><SelectTrigger aria-label="Filter alert severity"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All severities</SelectItem>{severities.map((value) => <SelectItem key={value} value={value}>{label(value)}</SelectItem>)}</SelectContent></Select></div></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}{alerts === null ? <div className="flex items-center gap-2 py-12 text-sm text-muted-foreground"><Loader2 className="animate-spin" /> Loading alerts...</div> : visible.length === 0 ? <div className="flex items-center gap-2 rounded-lg border border-dashed border-border py-12 text-sm text-muted-foreground"><AlertTriangle className="ml-5" /> No alerts match these filters.</div> : <div className="flex flex-col gap-2">{visible.map((alert) => <article key={alert.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-border bg-card p-3.5"><AlertTriangle className={alert.severity === "critical" ? "text-destructive" : alert.severity === "warning" ? "text-amber-500" : "text-primary"} aria-hidden="true" /><div className="min-w-48 flex-1"><div className="font-medium">{alert.summary}</div><div className="mt-0.5 text-xs text-muted-foreground">{label(alert.severity)} · {label(alert.state)} · Last seen {new Date(alert.lastSeen).toLocaleString()}</div></div><span className="text-xs font-medium uppercase">{label(alert.category)}</span>{alert.state === "active" ? <Button size="sm" variant="outline" onClick={() => acknowledge(alert.id)} aria-label={`Acknowledge ${alert.summary}`}><Check /> Acknowledge</Button> : null}</article>)}</div>}</div>;
}
