import type { NetworkVisibility, StorageVisibility, SystemVisibility } from "@/types/snapshot";

const unavailable = <p className="text-sm text-muted-foreground">Unavailable for this refresh.</p>;
const bytes = (value?: number) => value === undefined ? "Unknown" : `${(value / 1073741824).toFixed(1)} GiB`;

export function DeviceVisibility({ network, storage, system }: { network?: NetworkVisibility; storage?: StorageVisibility; system?: SystemVisibility }) {
  return <div className="grid grid-cols-1 gap-3.5 xl:grid-cols-3">
    <section className="rounded-lg border border-border bg-card p-3.5"><h2 className="mb-2 text-xs font-bold tracking-wide text-muted-foreground">NETWORK</h2>{!network ? unavailable : network.interfaces.length === 0 ? <p className="text-sm text-muted-foreground">No interfaces reported.</p> : <div className="space-y-2 text-xs">{network.interfaces.map((item) => <div key={item.name} className="rounded border border-border/60 p-2"><div className="font-semibold text-foreground">{item.name} <span className="font-normal text-muted-foreground">({item.linkState})</span></div><div className="mt-1 font-mono text-muted-foreground">{item.ipv4Addresses.concat(item.ipv6Addresses).join(", ") || "No addresses reported"}</div>{item.macAddress ? <div className="mt-1 text-muted-foreground">MAC: {item.macAddress}</div> : null}</div>)}<p className="text-muted-foreground">Default route: {network.defaultRoute ? `${network.defaultRoute.interface}${network.defaultRoute.gateway ? ` via ${network.defaultRoute.gateway}` : " (no gateway reported)"}` : "Unavailable"}</p><p className="text-muted-foreground">DNS: {network.dnsServers.join(", ") || "Unavailable"}</p></div>}</section>
    <section className="rounded-lg border border-border bg-card p-3.5"><h2 className="mb-2 text-xs font-bold tracking-wide text-muted-foreground">STORAGE</h2>{!storage ? unavailable : storage.filesystems.length === 0 ? <p className="text-sm text-muted-foreground">No primary filesystems reported.</p> : <div className="space-y-2 text-xs">{storage.filesystems.map((fs) => <div key={`${fs.source}:${fs.mountPoint}`} className="rounded border border-border/60 p-2"><div className="font-semibold text-foreground">{fs.mountPoint} {fs.mountPoint === "/" ? "(root)" : ""}</div><div className="text-muted-foreground">{fs.source} · {fs.filesystemType} · {fs.readOnly === undefined ? "access unknown" : fs.readOnly ? "read-only" : "read-write"}</div><div className="mt-1 text-muted-foreground">{fs.usagePercent === undefined ? "Usage unknown" : `${fs.usagePercent}% used`} · {bytes(fs.usedBytes)} / {bytes(fs.totalBytes)}</div></div>)}</div>}</section>
    <section className="rounded-lg border border-border bg-card p-3.5"><h2 className="mb-2 text-xs font-bold tracking-wide text-muted-foreground">SYSTEM</h2>{!system ? unavailable : <dl className="grid grid-cols-2 gap-x-3 gap-y-2 text-xs"><Row label="Hostname" value={system.hostname}/><Row label="OS" value={system.operatingSystem}/><Row label="Kernel" value={system.kernelVersion}/><Row label="Architecture" value={system.architecture}/><Row label="Model" value={system.model}/><Row label="CPU" value={system.cpuModel}/><Row label="Cores" value={system.logicalCoreCount?.toString()}/><Row label="Memory" value={bytes(system.totalMemoryBytes)}/></dl>}</section>
  </div>;
}
function Row({ label, value }: { label: string; value?: string }) { return <div><dt className="text-muted-foreground">{label}</dt><dd className="mt-0.5 text-foreground">{value || "Unavailable"}</dd></div>; }
