import { useCallback, useEffect, useMemo, useState, type KeyboardEvent, type ReactNode } from "react";
import { Activity, ArrowLeft, ExternalLink, Loader2, RefreshCw, Settings, TerminalSquare } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { useRouter } from "@/app/router";
import { diagnoseDeviceConnection, getDevice, openDeviceService, openDeviceTerminal } from "@/lib/tauri/devices";
import { refreshDevice } from "@/lib/tauri/monitoring";
import { useDeviceSnapshots } from "@/stores/useDeviceSnapshots";
import { useDeviceActivity } from "@/stores/useDeviceActivity";
import { formatUptime } from "@/lib/formatting/uptime";
import { formatRelativeTime } from "@/lib/formatting/relativeTime";
import { memoryPercent } from "@/lib/formatting/deviceMetrics";
import { connectionStatusColorClass, connectionStatusLabel } from "@/lib/formatting/connectionStatus";
import { containerHealthColorClass, containerHealthLabel, containerStateColorClass, containerStateLabel, formatPorts } from "@/lib/formatting/containerStatus";
import { DiagnosticsList, HealthDetails, PowerThrottling } from "@/features/devices/HealthDiagnostics";
import { ServiceHealthBadge, ServiceHealthDetails } from "@/features/services/ServiceHealth";
import { ContainerActionsCell } from "@/features/devices/ContainerActionsCell";
import { ContainerDetailDialog } from "@/features/containers/ContainerDetailDialog";
import { DeviceAdministration } from "@/features/devices/DeviceAdministration";
import { DeviceVisibility } from "@/features/devices/DeviceVisibility";
import { HistoricalTrends } from "@/features/monitoring/HistoricalTrends";
import { useTerminalSessions } from "@/stores/useTerminalSessions";
import type { ConnectivityDiagnosticReport } from "@/types/snapshot";
import type { Device } from "@/types/device";

const TABS = ["overview", "monitoring", "services", "containers", "system", "activity"] as const;
type Tab = (typeof TABS)[number];
const DEVICE_TRENDS = [{ label: "CPU usage", metric: "cpuUsagePercent", unit: "%" }, { label: "Memory usage", metric: "memoryUsagePercent", unit: "%" }, { label: "Root filesystem", metric: "rootFilesystemUsagePercent", unit: "%" }, { label: "Temperature", metric: "temperatureCelsius", unit: "°C" }, { label: "Device health", metric: "deviceHealth", unit: "" }] as const;

export function DeviceDetailScreen({ deviceId, initialContainerId }: { deviceId: string; initialContainerId?: string }) {
  const { goDashboard, goDeviceSettings } = useRouter(); const { openTerminal } = useTerminalSessions();
  const [device, setDevice] = useState<Device | null>(); const [tab, setTab] = useState<Tab>("overview"); const [refreshing, setRefreshing] = useState(false); const [diagnostics, setDiagnostics] = useState<ConnectivityDiagnosticReport | null>(null); const [diagnosing, setDiagnosing] = useState(false); const [selectedContainerId, setSelectedContainerId] = useState<string | null>(initialContainerId ?? null); const [serviceError, setServiceError] = useState<string | null>(null);
  const snapshots = useDeviceSnapshots(useMemo(() => [deviceId], [deviceId])); const snapshot = snapshots[deviceId];
  const load = useCallback(() => getDevice(deviceId).then(setDevice).catch(() => setDevice(null)), [deviceId]); useEffect(() => { void load(); }, [load]);
  if (device === undefined) return <Loading />; if (device === null) return <div className="flex flex-col gap-4"><Back onClick={goDashboard} /><p className="rounded-lg border border-border bg-card p-6 text-sm text-muted-foreground">This device could not be found. It may have been deleted.</p></div>;
  const metrics=snapshot?.metrics, containers=snapshot?.containers ?? [], online=snapshot?.connectionStatus === "online";
  const choose=(next:Tab)=>setTab(next); const key=(event:KeyboardEvent<HTMLButtonElement>, current:Tab)=>{ const direction=event.key==="ArrowRight"?1:event.key==="ArrowLeft"?-1:0; if(!direction)return; event.preventDefault(); choose(TABS[(TABS.indexOf(current)+direction+TABS.length)%TABS.length]); };
  return <div className="flex min-w-0 flex-col gap-3.5">
    <header className="flex flex-wrap items-center gap-2.5"><Back onClick={goDashboard}/><span className={cn("size-2.5 rounded-full", online ? "bg-status-healthy" : "bg-status-offline")}/><h1 className="text-lg font-semibold">{device.name}</h1>{snapshot ? <span className={cn("rounded-full bg-white/[.06] px-2 py-.5 text-xs",connectionStatusColorClass(snapshot.connectionStatus))}>{connectionStatusLabel(snapshot.connectionStatus)}</span>:null}<div className="flex-1"/><Button onClick={()=>openTerminal(device.id,device.name)}><TerminalSquare/>Open Terminal</Button><Button size="icon" variant="outline" title="Open external terminal" onClick={()=>openDeviceTerminal(deviceId)}><ExternalLink/></Button><Button size="icon" variant="outline" title="Refresh" disabled={refreshing} onClick={async()=>{setRefreshing(true);try{await refreshDevice(deviceId)}finally{setRefreshing(false)}}}>{refreshing?<Loader2 className="animate-spin"/>:<RefreshCw/>}</Button><Button size="icon" variant="outline" title="Device settings" onClick={()=>goDeviceSettings(deviceId)}><Settings/></Button></header>
    <DeviceAdministration deviceId={deviceId} deviceName={device.name}/>
    <div role="tablist" aria-label="Device detail sections" className="flex min-w-0 gap-1 overflow-x-auto rounded-lg border border-border bg-card p-1">{TABS.map(item=><button key={item} id={`device-tab-${item}`} type="button" role="tab" aria-selected={tab===item} aria-controls={`device-panel-${item}`} tabIndex={tab===item?0:-1} onClick={()=>choose(item)} onKeyDown={event=>key(event,item)} className={cn("shrink-0 rounded px-3 py-1.5 text-xs font-semibold capitalize focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",tab===item?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-accent")}>{item}</button>)}</div>
    {tab==="overview"?<Panel tab="overview"><div className="flex flex-col gap-3.5">{snapshot?<HealthDetails health={snapshot.health}/>:null}<section className="rounded-lg border border-border bg-card p-3.5"><h2 className="text-xs font-bold text-muted-foreground">OVERVIEW</h2><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><Info label="Hostname" value={metrics?.hostname??device.host}/><Info label="Model" value={metrics?.model??"—"}/><Info label="CPU" value={metrics?.cpuUsagePercent===undefined?"—":`${Math.round(metrics.cpuUsagePercent)}%`}/><Info label="Memory" value={metrics?`${Math.round(memoryPercent(metrics)??0)}%`:"—"}/><Info label="Temperature" value={metrics?.temperatureCelsius===undefined?"—":`${Math.round(metrics.temperatureCelsius)}°C`}/><Info label="Uptime" value={metrics?.uptimeSeconds===undefined?"—":formatUptime(metrics.uptimeSeconds)}/><Info label="Containers" value={`${containers.filter(item=>item.state==="running").length}/${containers.length}`}/><Info label="Last refresh" value={formatRelativeTime(snapshot?.capturedAt)}/></div></section></div></Panel>:null}
    {tab==="monitoring"?<Panel tab="monitoring"><Button variant="outline" size="sm" disabled={diagnosing} onClick={async()=>{setDiagnosing(true);try{setDiagnostics(await diagnoseDeviceConnection({host:device.host,sshPort:device.sshPort,sshUsername:device.sshUsername}))}finally{setDiagnosing(false)}}}>{diagnosing?<Loader2 className="animate-spin"/>:<Activity/>}Run connection diagnostics</Button>{diagnostics?<DiagnosticsList diagnostics={diagnostics}/>:null}{snapshot?<PowerThrottling health={snapshot.health}/>:null}<HistoricalTrends deviceId={deviceId} trends={DEVICE_TRENDS}/></Panel>:null}
    {tab==="services"?<Panel tab="services"><section><h2 className="mb-2 text-xs font-bold text-muted-foreground">SERVICES ON THIS DEVICE</h2>{device.services.length===0?<p className="rounded-lg border border-dashed border-border p-5 text-sm text-muted-foreground">No services registered on this device yet.</p>:<div className="flex flex-wrap gap-2.5">{device.services.map(service=><div key={service.id} className="min-w-[260px] rounded-lg border border-border bg-card p-3"><Button variant="ghost" className="w-full justify-start" disabled={!service.enabled} onClick={async()=>{try{await openDeviceService(deviceId,service.id)}catch{setServiceError("Could not open this service.")}}}>{service.name}</Button>{service.enabled?<><ServiceHealthDetails health={snapshot?.serviceHealth?.[service.id]}/><ServiceHealthBadge health={snapshot?.serviceHealth?.[service.id]}/></>:<Badge>Disabled</Badge>}</div>)}</div>}{serviceError?<p className="text-sm text-destructive">{serviceError}</p>:null}</section></Panel>:null}
    {tab==="containers"?<Panel tab="containers"><section className="rounded-lg border border-border bg-card p-3.5"><h2 className="mb-2 text-xs font-bold text-muted-foreground">DOCKER CONTAINERS</h2>{!online?<p className="text-sm text-muted-foreground">Device is offline — container status unavailable.</p>:!snapshot?.dockerAvailable?<p className="text-sm text-muted-foreground">Docker is not available on this device.</p>:containers.length===0?<p className="text-sm text-muted-foreground">No containers found on this device.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr><th>NAME</th><th>STATUS</th><th>HEALTH</th><th>PORT</th><th>ACTIONS</th></tr></thead><tbody>{containers.map(item=><tr key={item.id}><td><button type="button" onClick={()=>setSelectedContainerId(item.id)}>{item.name}</button></td><td className={containerStateColorClass(item.state)}>{containerStateLabel(item.state)}</td><td className={containerHealthColorClass(item.health)}>{containerHealthLabel(item.health)}</td><td>{formatPorts(item.ports)}</td><td><ContainerActionsCell deviceId={deviceId} containerId={item.id} containerName={item.name} state={item.state}/></td></tr>)}</tbody></table></div>}</section><ContainerDetailDialog deviceId={deviceId} container={containers.find(item=>item.id===selectedContainerId)??null} onOpenChange={open=>{if(!open)setSelectedContainerId(null)}} services={device.services}/></Panel>:null}
    {tab==="system"?<Panel tab="system"><DeviceVisibility network={snapshot?.networkVisibility} storage={snapshot?.storageVisibility} system={snapshot?.systemVisibility}/></Panel>:null}
    {tab==="activity"?<Panel tab="activity"><ActivityPanel deviceId={deviceId}/></Panel>:null}
  </div>;
}
function Panel({tab,children}:{tab:Tab;children:ReactNode}){return <div id={`device-panel-${tab}`} role="tabpanel" aria-labelledby={`device-tab-${tab}`} className="min-w-0">{children}</div>}
function ActivityPanel({deviceId}:{deviceId:string}){const activity=useDeviceActivity(deviceId);return <section className="flex max-h-[340px] flex-col rounded-lg border border-border bg-card p-3.5"><h2 className="mb-2 text-xs font-bold text-muted-foreground">RECENT ACTIVITY</h2>{activity.length===0?<p className="text-sm text-muted-foreground">No meaningful activity recorded for this device yet.</p>:<div className="overflow-y-auto">{activity.map(entry=><p key={entry.id} className="py-1 text-sm">{entry.summary} <span className="text-xs text-muted-foreground">{formatRelativeTime(entry.timestamp)}</span></p>)}</div>}</section>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm">{value}</p></div>}
function Loading(){return <div className="flex justify-center gap-2 py-16 text-sm text-muted-foreground"><Loader2 className="animate-spin"/>Loading…</div>}
function Back({onClick}:{onClick:()=>void}){return <button type="button" onClick={onClick} aria-label="Back to dashboard" className="flex size-[30px] items-center justify-center rounded-md border border-border focus-visible:ring-2 focus-visible:ring-ring"><ArrowLeft className="size-4"/></button>}
