import { useEffect, useState } from "react";
import { getHistoricalSeries } from "@/lib/tauri/monitoring";
import type { HistoricalMetric, HistoricalRange, HistoricalSeries } from "@/types/snapshot";
const ranges: { value: HistoricalRange; label: string }[] = [{ value: "oneHour", label: "1h" }, { value: "twentyFourHours", label: "24h" }, { value: "sevenDays", label: "7d" }, { value: "thirtyDays", label: "30d" }];
export function HistoricalTrends({ deviceId, entityId, trends }: { deviceId: string; entityId?: string; trends: readonly { label: string; metric: HistoricalMetric; unit: string }[] }) {
 const [range,setRange]=useState<HistoricalRange>("twentyFourHours"),[series,setSeries]=useState<Record<string,HistoricalSeries>>({}),[error,setError]=useState(false); const metrics=trends.map(t=>t.metric).join("\0");
 useEffect(()=>{let active=true;Promise.all(metrics.split("\0").map(async metric=>[metric,await getHistoricalSeries(deviceId,entityId,metric as HistoricalMetric,range)] as const)).then(items=>{if(active){setSeries(Object.fromEntries(items));setError(false)}}).catch(()=>active&&setError(true));return()=>{active=false}},[deviceId,entityId,metrics,range]);
 return <section className="min-w-0 overflow-hidden rounded-lg border border-border bg-card p-3.5" aria-label="Historical monitoring"><div className="mb-3 flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-xs font-bold tracking-wide text-muted-foreground">HISTORICAL TRENDS</h2><p className="text-xs text-muted-foreground">Local samples, retained for 30 days.</p></div><div className="flex max-w-full gap-1 overflow-x-auto">{ranges.map(item=><button key={item.value} type="button" className={`shrink-0 rounded px-2 py-1 text-xs ${range===item.value?"bg-primary text-primary-foreground":"border border-border"}`} onClick={()=>setRange(item.value)}>{item.label}</button>)}</div></div>{error?<p className="text-sm text-destructive">Historical data could not be loaded. Current monitoring remains available.</p>:<div className="grid min-w-0 gap-3 md:grid-cols-2">{trends.map(trend=><Trend key={trend.metric} label={trend.label} unit={trend.unit} series={series[trend.metric]}/>)}</div>}</section>
}
function Trend({label,unit,series}:{label:string;unit:string;series?:HistoricalSeries}){if(!series)return <div className="min-w-0 rounded border border-border p-2 text-xs">Loading {label}…</div>;if(!series.numericPoints.length&&!series.statePoints.length)return <div className="min-w-0 rounded border border-border p-2 text-xs">No historical samples in this range.</div>;if(series.statePoints.length)return <div className="min-w-0 overflow-hidden rounded border border-border p-2 text-xs break-words">{series.statePoints.map(point=><p key={`${point.timestamp}-${point.state}`}>{point.state}</p>)}</div>;const values=series.numericPoints.map(point=>point.value),low=Math.min(...values),high=Math.max(...values);return <div className="min-w-0 overflow-hidden rounded border border-border p-2 text-xs"><p className="font-semibold">{label}</p><div className="mt-2 flex h-12 min-w-0 items-end gap-px" aria-label={`${label} chart; ${series.numericPoints.length} samples`}>{series.numericPoints.map(point=><span key={point.timestamp} className="min-w-0 flex-1 bg-primary/70" style={{height:`${high===low?50:12+((point.value-low)/(high-low))*88}%`}}/>)}</div><p className="mt-1 break-words text-muted-foreground">{series.numericPoints.length} samples · {low.toFixed(1)}–{high.toFixed(1)}{unit}</p></div>}
