import { useEffect, useState } from "react";
import { getHistoricalSeries } from "@/lib/tauri/monitoring";
import type { HistoricalMetric, HistoricalRange, HistoricalSeries } from "@/types/snapshot";

const ranges: { value: HistoricalRange; label: string }[] = [{ value: "oneHour", label: "1h" }, { value: "twentyFourHours", label: "24h" }, { value: "sevenDays", label: "7d" }, { value: "thirtyDays", label: "30d" }];
export function HistoricalTrends({ deviceId, entityId, trends }: { deviceId: string; entityId?: string; trends: { label: string; metric: HistoricalMetric; unit: string }[] }) {
  const [range, setRange] = useState<HistoricalRange>("twentyFourHours"); const [series, setSeries] = useState<Record<string, HistoricalSeries>>({}); const [error, setError] = useState(false);
  // Callers commonly construct their display definitions inline. The request
  // identity is the selected metrics, not the array instance or display text.
  // This keeps a parent re-render from re-querying unchanged history while
  // retaining re-query behavior for an actual metric configuration change.
  const metricConfiguration = trends.map((trend) => trend.metric).join("\u0000");
  useEffect(() => { const metrics = metricConfiguration.split("\u0000") as HistoricalMetric[]; let active = true; Promise.all(metrics.map(async metric => [metric, await getHistoricalSeries(deviceId, entityId, metric, range)] as const)).then(items => { if (active) { setSeries(Object.fromEntries(items)); setError(false); } }).catch(() => { if (active) setError(true); }); return () => { active = false; }; }, [deviceId, entityId, metricConfiguration, range]);
  return <section className="rounded-lg border border-border bg-card p-3.5" aria-label="Historical monitoring"><div className="mb-3 flex items-center justify-between gap-2"><div><h2 className="text-xs font-bold tracking-wide text-muted-foreground">HISTORICAL TRENDS</h2><p className="text-xs text-muted-foreground">Local samples, retained for 30 days.</p></div><div className="flex gap-1">{ranges.map(item => <button key={item.value} type="button" className={`rounded px-2 py-1 text-xs ${range === item.value ? "bg-primary text-primary-foreground" : "border border-border"}`} onClick={() => setRange(item.value)}>{item.label}</button>)}</div></div>{error ? <p className="text-sm text-destructive">Historical data could not be loaded. Current monitoring remains available.</p> : <div className="grid gap-3 md:grid-cols-2">{trends.map(trend => <Trend key={trend.metric} label={trend.label} unit={trend.unit} series={series[trend.metric]} />)}</div>}</section>;
}
function Trend({ label, unit, series }: { label: string; unit: string; series?: HistoricalSeries }) { if (!series) return <div className="rounded border border-border p-2 text-xs text-muted-foreground">Loading {label}…</div>; if (!series.numericPoints.length && !series.statePoints.length) return <div className="rounded border border-border p-2 text-xs"><p className="font-semibold">{label}</p><p className="text-muted-foreground">No historical samples in this range.</p></div>; if (series.statePoints.length) return <div className="rounded border border-border p-2 text-xs"><p className="font-semibold">{label}</p><ol className="mt-1 space-y-1">{series.statePoints.map(point => <li key={`${point.timestamp}-${point.state}`}><time>{new Date(point.timestamp).toLocaleString()}</time>: {point.state}</li>)}</ol></div>; const values=series.numericPoints.map(point=>point.value); const low=Math.min(...values), high=Math.max(...values); return <div className="rounded border border-border p-2 text-xs"><p className="font-semibold">{label}</p><div className="mt-2 flex h-12 items-end gap-px" aria-label={`${label} chart; ${series.numericPoints.length} samples`}>{series.numericPoints.map(point => <span key={point.timestamp} title={`${new Date(point.timestamp).toLocaleString()}: ${point.value.toFixed(1)}${unit} (min ${point.minimum.toFixed(1)}, max ${point.maximum.toFixed(1)})`} className="min-w-1 flex-1 bg-primary/70" style={{ height: `${high === low ? 50 : 12 + ((point.value - low) / (high - low)) * 88}%` }} />)}</div><p className="mt-1 text-muted-foreground">{series.numericPoints.length} samples · {low.toFixed(1)}–{high.toFixed(1)}{unit}</p></div>; }
