use super::*;
use crate::{domain::{activity::ActivityEvent,device::{Device,DeviceType},managed_workload::{ManagedWorkload,ManagedWorkloadFile},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState}},infrastructure::ssh::{RemoteExecutionResult,RemoteOperation,SshError},storage::{activity_repository::{ActivityRepository,JsonActivityRepository},device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_operation_repository::JsonManagedWorkloadOperationRepository,managed_workload_repository::{JsonManagedWorkloadRepository,ManagedWorkloadRepository}}};
use std::{collections::VecDeque,fs,sync::Mutex,time::Duration};
struct Script{replies:Mutex<VecDeque<Result<RemoteExecutionResult,SshError>>>,commands:Mutex<Vec<String>>}
impl RemoteExecutor for Script{fn execute(&self,_:&SshTarget,command:&str,_:Duration)->Result<RemoteExecutionResult,SshError>{self.commands.lock().unwrap().push(command.into());self.replies.lock().unwrap().pop_front().expect("script reply")}}
fn reply(stdout:&str)->Result<RemoteExecutionResult,SshError>{Ok(RemoteExecutionResult{exit_code:Some(0),stdout:stdout.into(),stderr:"FAKE_DOCKER_STDERR_SECRET".into(),duration_ms:1,timed_out:false})}
fn container(project:&str,service:&str,state:&str,status:&str,id:&str)->String{format!(r#"{{"ID":"{id}","Names":"untrusted-display-name","Image":"image","State":"{state}","Status":"{status}","Ports":"","CreatedAt":"","Labels":"com.docker.compose.project={project},com.docker.compose.service={service},token=FAKE_TOKEN"}}"#)}
fn output(lines:Vec<String>)->String{format!("PIHUB_DOCKER_AVAILABLE=1\n{}\n",lines.join("\n"))}
fn operation()->ManagedWorkloadOperation{ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:1,trusted_action_digest:"a".repeat(64),target_revision:"b".repeat(40),deployment_fingerprint:"c".repeat(64),transient_unit_id:Some(format!("pihub-workload-{}.service","d".repeat(32))),dispatch_state:ManagedWorkloadDispatchState::Accepted,state:ManagedWorkloadOperationState::RevisionVerified,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:Some("2099-01-01T00:00:00Z".into()),completed_at:None,failure:None,initiated_activity_emitted:true,failure_activity_emitted:false,completion_activity_emitted:false}}
fn setup(services:&[&str],reply_value:Result<RemoteExecutionResult,SshError>)->(tempfile::TempDir,ManagedWorkloadOperation,Script){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services:vec![],created_at:"x".into(),updated_at:"x".into()};let workload=ManagedWorkload{id:"finance".into(),device_id:"pi5".into(),name:"Finance".into(),action_id:"personal-finance".into(),compose_project:Some("finance".into()),required_compose_services:services.iter().map(|s|(*s).into()).collect(),required_service_health_ids:vec![],enabled:true,config_revision:1};let operation=operation();JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();JsonManagedWorkloadRepository::new(dir.path()).save(&ManagedWorkloadFile{schema_version:1,workloads:vec![workload]}).unwrap();JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();(dir,operation,Script{replies:Mutex::new(VecDeque::from(vec![reply_value])),commands:Mutex::new(vec![])})}
fn activities(dir:&std::path::Path)->Vec<ActivityEvent>{JsonActivityRepository::new(dir).load_all()}
fn assert_fixed(script:&Script){let commands=script.commands.lock().unwrap();assert_eq!(commands.as_slice(),[RemoteOperation::WorkloadRuntime.command().unwrap().to_string()]);for command in commands.iter(){for forbidden in [" apply","systemd-run","docker exec","docker compose","docker up","docker down","docker restart","docker pull","docker build","docker rm","docker start","docker stop"]{assert!(!command.contains(forbidden),"unexpected {forbidden}");}assert!(!command.contains("finance")&&!command.contains("app")&&!command.contains("api"));}}

#[test]
fn revision_verified_all_required_compose_services_running_passes_without_completion(){let(dir,operation,script)=setup(&["app","api"],reply(&output(vec![container("finance","app","running","Up (healthy)","a"),container("finance","api","running","Up","b")])));let result=verify_workload_runtime_with(dir.path(),&operation,&script).unwrap();assert_eq!(result.state,ManagedWorkloadOperationState::WorkloadRuntimeVerified);assert_ne!(result.state,ManagedWorkloadOperationState::Completed);assert!(result.completed_at.is_none());assert_eq!(JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance"),Some(result));assert!(activities(dir.path()).is_empty());assert_fixed(&script);let raw=fs::read_to_string(dir.path().join("managed-workload-operations.json")).unwrap();for value in ["FAKE_DOCKER_STDERR_SECRET","FAKE_TOKEN","untrusted-display-name","docker ps","com.docker.compose"]{assert!(!raw.contains(value),"persisted {value}");}}

#[test]
fn missing_stopped_unhealthy_and_ambiguous_compose_identities_fail_closed(){let cases=[(output(vec![container("other","app","running","Up","a")]),RuntimeVerificationError::ProjectMissing),(output(vec![container("finance","other","running","Up","a")]),RuntimeVerificationError::ServiceMissing),(output(vec![container("finance","app","exited","Exited","a")]),RuntimeVerificationError::ContainerNotRunning),(output(vec![container("finance","app","running","Up (unhealthy)","a")]),RuntimeVerificationError::DockerHealthFailed),(output(vec![container("finance","app","running","Up","a"),container("finance","app","running","Up","b")]),RuntimeVerificationError::AmbiguousIdentity)];for(raw,expected)in cases{let(dir,operation,script)=setup(&["app"],reply(&raw));assert_eq!(verify_workload_runtime_with(dir.path(),&operation,&script),Err(expected));let persisted=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(persisted.state,ManagedWorkloadOperationState::VerificationFailed);assert_eq!(persisted.failure,Some(ManagedWorkloadFailure::VerificationFailed));assert!(!persisted.requires_recovery());assert!(activities(dir.path()).is_empty());assert_fixed(&script);}}

#[test]
fn unavailable_and_bounded_transport_failures_persist_without_mutation(){let cases=[(reply("PIHUB_DOCKER_AVAILABLE=0\n"),RuntimeVerificationError::DockerUnavailable),(Err(SshError::ConnectionRefused),RuntimeVerificationError::TransportFailed),(Err(SshError::RemoteCommandTimeout),RuntimeVerificationError::TimedOut),(Err(SshError::OutputLimitExceeded),RuntimeVerificationError::OutputLimitExceeded)];for(reply_value,expected)in cases{let(dir,operation,script)=setup(&["app"],reply_value);assert_eq!(verify_workload_runtime_with(dir.path(),&operation,&script),Err(expected));assert_eq!(JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap().state,ManagedWorkloadOperationState::VerificationFailed);assert_fixed(&script);}}

#[test]
fn runtime_gate_rejects_wrong_lifecycle_without_a_caller_identity_surface(){let(dir,mut operation,script)=setup(&["app"],reply(""));operation.state=ManagedWorkloadOperationState::AwaitingVerification;JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();assert_eq!(verify_workload_runtime_with(dir.path(),&operation,&script),Err(RuntimeVerificationError::InvalidLifecycle));assert!(script.commands.lock().unwrap().is_empty());}
