use super::*;
use crate::{domain::{activity::ActivityEvent,device::{Device,DeviceType},managed_workload::{ManagedWorkload,ManagedWorkloadFile},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState}},infrastructure::ssh::{RemoteExecutionResult,SshError},storage::{activity_repository::{ActivityRepository,JsonActivityRepository},device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_operation_repository::JsonManagedWorkloadOperationRepository,managed_workload_repository::{JsonManagedWorkloadRepository,ManagedWorkloadRepository}}};
use std::{collections::VecDeque,fs,sync::Mutex,time::Duration};
struct Script{replies:Mutex<VecDeque<Result<RemoteExecutionResult,SshError>>>,commands:Mutex<Vec<String>>}
impl RemoteExecutor for Script{fn execute(&self,_:&SshTarget,command:&str,_:Duration)->Result<RemoteExecutionResult,SshError>{self.commands.lock().unwrap().push(command.into());self.replies.lock().unwrap().pop_front().expect("script reply")}}
fn reply(stdout:&str)->Result<RemoteExecutionResult,SshError>{Ok(RemoteExecutionResult{exit_code:Some(0),stdout:stdout.into(),stderr:"FAKE_VERIFY_STDERR_SECRET".into(),duration_ms:1,timed_out:false})}
fn trust(digest:&str)->Result<RemoteExecutionResult,SshError>{reply(&format!("PIHUB_M17_TRUST=trusted\nPIHUB_M17_ACTION_DIGEST={digest}\n"))}
fn operation()->ManagedWorkloadOperation{ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:1,trusted_action_digest:"a".repeat(64),target_revision:"b".repeat(40),deployment_fingerprint:"c".repeat(64),transient_unit_id:Some(format!("pihub-workload-{}.service","d".repeat(32))),dispatch_state:ManagedWorkloadDispatchState::Accepted,state:ManagedWorkloadOperationState::AwaitingVerification,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:Some("2099-01-01T00:00:00Z".into()),completed_at:None,failure:None,initiated_activity_emitted:true,failure_activity_emitted:false}}
fn setup(replies:Vec<Result<RemoteExecutionResult,SshError>>)->(tempfile::TempDir,ManagedWorkloadOperation,Script){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services:vec![],created_at:"x".into(),updated_at:"x".into()};let workload=ManagedWorkload{id:"finance".into(),device_id:"pi5".into(),name:"Finance".into(),action_id:"personal-finance".into(),compose_project:Some("finance".into()),required_compose_services:vec!["app".into()],required_service_health_ids:vec![],enabled:true,config_revision:1};let operation=operation();JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();JsonManagedWorkloadRepository::new(dir.path()).save(&ManagedWorkloadFile{schema_version:1,workloads:vec![workload]}).unwrap();JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();(dir,operation,Script{replies:Mutex::new(VecDeque::from(replies)),commands:Mutex::new(vec![])})}
fn verify_ok(revision:&str)->Result<RemoteExecutionResult,SshError>{reply(&format!(r#"{{"protocolVersion":1,"status":"ok","deployedRevision":"{revision}"}}"#))}
fn activity(dir:&std::path::Path)->Vec<ActivityEvent>{JsonActivityRepository::new(dir).load_all()}

#[test]
fn awaiting_verification_exact_revision_passes_only_the_revision_gate(){let(dir,operation,script)=setup(vec![trust(&"a".repeat(64)),verify_ok(&"b".repeat(40))]);let result=verify_deployed_revision_with(dir.path(),&operation,&script).unwrap();assert_eq!(result.state,ManagedWorkloadOperationState::RevisionVerified);assert_ne!(result.state,ManagedWorkloadOperationState::Completed);assert!(result.completed_at.is_none());assert_eq!(JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance"),Some(result));assert!(activity(dir.path()).is_empty());let commands=script.commands.lock().unwrap();assert_eq!(commands.len(),2);assert!(commands[0].contains("PIHUB_M17_TRUST"));assert_eq!(commands[1],format!("'/usr/local/libexec/pi-hub/actions/personal-finance' verify {}","b".repeat(40)));assert!(!commands.iter().any(|c|c.contains(" apply")||c.contains("systemd-run")||c.contains("docker")||c.contains("compose")));drop(commands);let raw=fs::read_to_string(dir.path().join("managed-workload-operations.json")).unwrap();for value in ["verify ","/usr/local","FAKE_VERIFY_STDERR_SECRET","stdout","stderr","FAKE_SECRET_VALUE"]{assert!(!raw.contains(value),"persisted {value}");}}

#[test]
fn verification_rejects_mismatch_and_protocol_failures_without_retry_or_dispatch(){let cases=[(verify_ok(&"c".repeat(40)),VerificationError::DeployedRevisionMismatch),(reply("not-json"),VerificationError::ProtocolInvalid),(reply(r#"{"protocolVersion":2,"status":"ok","deployedRevision":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}"#),VerificationError::ProtocolUnsupported)];for(reply_value,expected)in cases{let(dir,operation,script)=setup(vec![trust(&"a".repeat(64)),reply_value]);assert_eq!(verify_deployed_revision_with(dir.path(),&operation,&script),Err(expected));let persisted=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(persisted.state,ManagedWorkloadOperationState::VerificationFailed);assert_eq!(persisted.failure,Some(ManagedWorkloadFailure::VerificationFailed));assert!(!persisted.requires_recovery());assert!(activity(dir.path()).is_empty());let calls=script.commands.lock().unwrap().len();assert_eq!(verify_deployed_revision_with(dir.path(),&persisted,&script),Err(VerificationError::InvalidLifecycle));assert_eq!(script.commands.lock().unwrap().len(),calls);assert!(!script.commands.lock().unwrap().iter().any(|c|c.contains(" apply")||c.contains("systemd-run")));}}

#[test]
fn trust_and_bounded_transport_failures_persist_verification_failure(){let failures=[(Err(SshError::ConnectionRefused),VerificationError::TransportFailed),(Err(SshError::RemoteCommandTimeout),VerificationError::TimedOut),(Err(SshError::OutputLimitExceeded),VerificationError::OutputLimitExceeded)];for(reply_value,expected)in failures{let(dir,operation,script)=setup(vec![trust(&"a".repeat(64)),reply_value]);assert_eq!(verify_deployed_revision_with(dir.path(),&operation,&script),Err(expected));let persisted=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(persisted.state,ManagedWorkloadOperationState::VerificationFailed);assert!(!script.commands.lock().unwrap().iter().any(|c|c.contains(" apply")||c.contains("systemd-run")));}let(dir,operation,script)=setup(vec![reply("PIHUB_M17_TRUST=trust_failure\n")]);assert_eq!(verify_deployed_revision_with(dir.path(),&operation,&script),Err(VerificationError::TrustFailed));assert_eq!(JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap().state,ManagedWorkloadOperationState::VerificationFailed);assert_eq!(script.commands.lock().unwrap().len(),1);}

#[test]
fn verification_requires_persisted_awaiting_operation_and_never_accepts_a_replacement_target(){let(dir,mut operation,script)=setup(vec![]);operation.state=ManagedWorkloadOperationState::Deploying;JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();assert_eq!(verify_deployed_revision_with(dir.path(),&operation,&script),Err(VerificationError::InvalidLifecycle));assert!(script.commands.lock().unwrap().is_empty());}
