use super::*;
use crate::{domain::{device::{Device,DeviceType},managed_workload::{ManagedWorkload,ManagedWorkloadFile},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState}},infrastructure::ssh::{RemoteExecutionResult,SshError},storage::{device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_repository::{ManagedWorkloadRepository,JsonManagedWorkloadRepository}}};
use std::{collections::VecDeque,sync::Mutex,time::Duration};

struct Script { replies: Mutex<VecDeque<Result<RemoteExecutionResult,SshError>>>, commands: Mutex<Vec<String>> }
impl RemoteExecutor for Script { fn execute(&self,_:&SshTarget,command:&str,_:Duration)->Result<RemoteExecutionResult,SshError>{self.commands.lock().unwrap().push(command.into());self.replies.lock().unwrap().pop_front().expect("script reply")} }
fn ok(stdout:String)->Result<RemoteExecutionResult,SshError>{Ok(RemoteExecutionResult{exit_code:Some(0),stdout,stderr:String::new(),duration_ms:1,timed_out:false})}
fn trust(digest:&str)->Result<RemoteExecutionResult,SshError>{ok(format!("PIHUB_M17_TRUST=trusted\nPIHUB_M17_ACTION_DIGEST={digest}\n"))}
fn prepare(target:&str)->Result<RemoteExecutionResult,SshError>{ok(format!(r#"{{"protocolVersion":1,"status":"ready","currentRevision":"{}","targetRevision":"{}","changeCount":1}}"#,"a".repeat(40),target))}
fn workload(revision:u32,service:&str)->ManagedWorkload{ManagedWorkload{id:"finance".into(),device_id:"pi5".into(),name:"Finance".into(),action_id:"personal-finance".into(),compose_project:Some("finance".into()),required_compose_services:vec![service.into()],required_service_health_ids:vec![],enabled:true,config_revision:revision}}
fn setup(current:ManagedWorkload,prepared_revision:u32,prepared_digest:&str,prepared_target:&str)->(tempfile::TempDir,ManagedWorkloadOperation){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services:vec![],created_at:"x".into(),updated_at:"x".into()};JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();JsonManagedWorkloadRepository::new(dir.path()).save(&ManagedWorkloadFile{schema_version:1,workloads:vec![current.clone()]}).unwrap();let prepared_workload=workload(prepared_revision,"app");let target=TargetRevision::parse(prepared_target).unwrap();let fingerprint=fingerprint(&prepared_workload.id,prepared_workload.config_revision,prepared_digest,&target,&verification(&prepared_workload)).0;(dir,ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:prepared_revision,trusted_action_digest:prepared_digest.into(),target_revision:prepared_target.into(),deployment_fingerprint:fingerprint,transient_unit_id:None,dispatch_state:ManagedWorkloadDispatchState::NotAttempted,state:ManagedWorkloadOperationState::Prepared,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:None,completed_at:None,failure:None})}
fn assert_no_dispatch(script:&Script){for command in script.commands.lock().unwrap().iter(){assert!(!command.contains(" apply")&&!command.contains("systemd-run"),"unexpected dispatch command: {command}");}}
fn assert_released(coordinator:&DeviceMaintenanceCoordinator){assert!(coordinator.try_claim("pi5",MaintenanceOperationKind::WorkloadDeploy).is_some());}

#[test]
fn unchanged_evidence_is_dispatch_eligible_and_releases_coordinator(){let digest="b".repeat(64);let target="c".repeat(40);let(dir,operation)=setup(workload(1,"app"),1,&digest,&target);let script=Script{replies:Mutex::new(VecDeque::from(vec![trust(&digest),prepare(&target)])),commands:Mutex::new(vec![])};let coordinator=DeviceMaintenanceCoordinator::new();assert!(matches!(revalidate_dispatch_consent_with(dir.path(),&operation,&script,&coordinator),Ok(DispatchConsent::DispatchEligible(_))));assert_no_dispatch(&script);assert_released(&coordinator);}
#[test]
fn consent_evidence_drift_returns_plan_changed_without_dispatch(){let digest="b".repeat(64);let target="c".repeat(40);for(current,fresh_digest,fresh_target)in[(workload(2,"app"),digest.clone(),target.clone()),(workload(1,"app"),"d".repeat(64),target.clone()),(workload(1,"app"),digest.clone(),"e".repeat(40)),(workload(1,"other"),digest.clone(),target.clone())]{let(dir,operation)=setup(current,1,&digest,&target);let script=Script{replies:Mutex::new(VecDeque::from(vec![trust(&fresh_digest),prepare(&fresh_target)])),commands:Mutex::new(vec![])};let coordinator=DeviceMaintenanceCoordinator::new();assert_eq!(revalidate_dispatch_consent_with(dir.path(),&operation,&script,&coordinator),Ok(DispatchConsent::PlanChanged));assert_no_dispatch(&script);assert_released(&coordinator);}}
#[test]
fn fresh_trust_or_prepare_failure_never_becomes_eligible_and_releases_coordinator(){let digest="b".repeat(64);let target="c".repeat(40);for replies in [vec![ok("PIHUB_M17_TRUST=trust_failure\n".into())],vec![trust(&digest),ok("not-json".into())]]{let(dir,operation)=setup(workload(1,"app"),1,&digest,&target);let script=Script{replies:Mutex::new(VecDeque::from(replies)),commands:Mutex::new(vec![])};let coordinator=DeviceMaintenanceCoordinator::new();assert!(matches!(revalidate_dispatch_consent_with(dir.path(),&operation,&script,&coordinator),Err(PrepareError::ActionTrustFailed|PrepareError::PrepareProtocolInvalid)));assert_no_dispatch(&script);assert_released(&coordinator);}}
