use super::*;
use crate::{domain::{device::{Device,DeviceType},managed_workload::{ManagedWorkload,ManagedWorkloadFile},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState}},infrastructure::ssh::{RemoteExecutionResult,SshError},storage::{device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_repository::{ManagedWorkloadRepository,JsonManagedWorkloadRepository},managed_workload_operation_repository::JsonManagedWorkloadOperationRepository}};
use std::{collections::VecDeque,fs,sync::Mutex,time::Duration};
struct Script{replies:Mutex<VecDeque<RemoteExecutionResult>>,commands:Mutex<Vec<String>>}
impl RemoteExecutor for Script{fn execute(&self,_:&SshTarget,command:&str,_:Duration)->Result<RemoteExecutionResult,SshError>{self.commands.lock().unwrap().push(command.into());Ok(self.replies.lock().unwrap().pop_front().unwrap())}}
fn ok(stdout:String)->RemoteExecutionResult{RemoteExecutionResult{exit_code:Some(0),stdout,stderr:"FAKE_STDERR_SECRET".into(),duration_ms:1,timed_out:false}}
fn workload()->ManagedWorkload{ManagedWorkload{id:"finance".into(),device_id:"pi5".into(),name:"Finance".into(),action_id:"personal-finance".into(),compose_project:Some("finance".into()),required_compose_services:vec!["app".into()],required_service_health_ids:vec![],enabled:true,config_revision:1}}
fn setup()->(tempfile::TempDir,ManagedWorkloadOperation,Script){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services:vec![],created_at:"x".into(),updated_at:"x".into()};let w=workload();JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();JsonManagedWorkloadRepository::new(dir.path()).save(&ManagedWorkloadFile{schema_version:1,workloads:vec![w.clone()]}).unwrap();let target=TargetRevision::parse(&"c".repeat(40)).unwrap();let operation=ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:1,trusted_action_digest:"b".repeat(64),target_revision:target.as_str().into(),deployment_fingerprint:fingerprint(&w.id,w.config_revision,&"b".repeat(64),&target,&verification(&w)).0,transient_unit_id:None,dispatch_state:ManagedWorkloadDispatchState::NotAttempted,state:ManagedWorkloadOperationState::Prepared,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:None,completed_at:None,failure:None,initiated_activity_emitted:false,failure_activity_emitted:false};let script=Script{replies:Mutex::new(VecDeque::from(vec![ok(format!("PIHUB_M17_TRUST=trusted\nPIHUB_M17_ACTION_DIGEST={}\n","b".repeat(64))),ok(format!(r#"{{"protocolVersion":1,"status":"ready","currentRevision":"{}","targetRevision":"{}","changeCount":1}}"#,"a".repeat(40),target.as_str()))])),commands:Mutex::new(vec![])};(dir,operation,script)}
fn eligible(dir:&std::path::Path,operation:&ManagedWorkloadOperation,script:&Script)->DispatchEligible{match revalidate_dispatch_consent_with(dir,operation,script,&DeviceMaintenanceCoordinator::new()).unwrap(){DispatchConsent::DispatchEligible(value)=>value,DispatchConsent::PlanChanged=>panic!("unexpected plan drift")}}
#[test]
fn dispatch_eligible_persists_dispatch_prepared_before_any_future_execution(){let(dir,operation,script)=setup();let eligible=eligible(dir.path(),&operation,&script);let calls=script.commands.lock().unwrap().len();let prepared=prepare_detached_dispatch(dir.path(),eligible).unwrap();assert_eq!(script.commands.lock().unwrap().len(),calls);assert_eq!(prepared.operation.state,ManagedWorkloadOperationState::DispatchPrepared);assert_eq!(prepared.operation.dispatch_state,ManagedWorkloadDispatchState::NotAttempted);assert!(prepared.operation.observation_deadline.is_some());assert!(prepared.operation.transient_unit_id.is_some());assert_eq!(JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance"),Some(prepared.operation.clone()));}
#[test]
fn generated_unit_is_backend_only_and_fixed_command_is_exact(){let(dir,operation,script)=setup();let prepared=prepare_detached_dispatch(dir.path(),eligible(dir.path(),&operation,&script)).unwrap();let unit=prepared.operation.transient_unit_id.as_deref().unwrap();assert!(ManagedWorkloadOperation::is_valid_transient_unit_id(unit));assert_eq!(unit.len(),55);assert!(fixed_detached_dispatch_command("caller.service","personal-finance",&TargetRevision::parse(&"c".repeat(40)).unwrap(),"deploy").is_none());assert_eq!(prepared.command,format!("sudo -n systemd-run --unit={unit} --service-type=exec --property=RemainAfterExit=yes --property=User=deploy -- /usr/local/libexec/pi-hub/actions/personal-finance apply {}","c".repeat(40)));assert!(!prepared.command.contains("sh -c")&&!prepared.command.contains(";")&&!prepared.command.contains("&&")&&!prepared.command.contains("--setenv"));}
#[test]
fn dispatch_preparation_never_executes_apply_or_persists_sensitive_command_data(){let(dir,operation,script)=setup();let prepared=prepare_detached_dispatch(dir.path(),eligible(dir.path(),&operation,&script)).unwrap();for command in script.commands.lock().unwrap().iter(){assert!(!command.contains(" apply")&&!command.contains("systemd-run"));}let raw=fs::read_to_string(dir.path().join("managed-workload-operations.json")).unwrap();for value in ["systemd-run","/usr/local","apply ","FAKE_STDERR_SECRET","FAKE_ENV=present","FAKE_SECRET_VALUE"]{assert!(!raw.contains(value),"persisted {value}");}assert!(prepared.command.contains("systemd-run"));}
