use super::*;
use crate::{domain::{device::{Device,DeviceType},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState}},infrastructure::ssh::{RemoteExecutionResult,SshError},storage::{activity_repository::{ActivityRepository,JsonActivityRepository},device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_operation_repository::JsonManagedWorkloadOperationRepository}};
use std::{collections::VecDeque,fs,sync::Mutex,time::Duration};

struct Script{replies:Mutex<VecDeque<Result<RemoteExecutionResult,SshError>>>,commands:Mutex<Vec<String>>}
impl RemoteExecutor for Script{fn execute(&self,_:&SshTarget,command:&str,_:Duration)->Result<RemoteExecutionResult,SshError>{self.commands.lock().unwrap().push(command.into());self.replies.lock().unwrap().pop_front().expect("script reply")}}
fn ok(stdout:&str)->Result<RemoteExecutionResult,SshError>{Ok(RemoteExecutionResult{exit_code:Some(0),stdout:stdout.into(),stderr:"FAKE_STDERR_SECRET".into(),duration_ms:1,timed_out:false})}
fn operation(state:ManagedWorkloadOperationState,dispatch_state:ManagedWorkloadDispatchState)->ManagedWorkloadOperation{ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:1,trusted_action_digest:"a".repeat(64),target_revision:"b".repeat(40),deployment_fingerprint:"c".repeat(64),transient_unit_id:Some(format!("pihub-workload-{}.service","d".repeat(32))),dispatch_state,state,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:Some("2099-01-01T00:00:00Z".into()),completed_at:None,failure:None,initiated_activity_emitted:false,failure_activity_emitted:false}}
fn setup(state:ManagedWorkloadOperationState,dispatch_state:ManagedWorkloadDispatchState,replies:Vec<Result<RemoteExecutionResult,SshError>>)->(tempfile::TempDir,ManagedWorkloadOperation,Script){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services:vec![],created_at:"x".into(),updated_at:"x".into()};JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();let operation=operation(state,dispatch_state);JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();(dir,operation,Script{replies:Mutex::new(VecDeque::from(replies)),commands:Mutex::new(vec![])})}
fn activities(dir:&std::path::Path)->Vec<ActivityEvent>{JsonActivityRepository::new(dir).load_all()}
fn running()->Result<RemoteExecutionResult,SshError>{ok("LoadState=loaded\nActiveState=active\nSubState=running\n")}

#[test]
fn accepted_dispatch_emits_one_sanitized_initiated_activity(){let(dir,mut operation,script)=setup(ManagedWorkloadOperationState::DispatchPrepared,ManagedWorkloadDispatchState::NotAttempted,vec![ok("")]);let target=TargetRevision::parse(&operation.target_revision).unwrap();let command=fixed_detached_dispatch_command(operation.transient_unit_id.as_deref().unwrap(),&operation.action_id,&target,"deploy").unwrap();let result=dispatch_prepared_with(dir.path(),DispatchPrepared{operation:operation.clone(),command,target:SshTarget{host:"host.example".into(),port:22,username:"deploy".into()}},&script).unwrap();assert_eq!(result.state,ManagedWorkloadOperationState::Deploying);assert!(result.initiated_activity_emitted);let entries=activities(dir.path());assert_eq!(entries.len(),1);assert_eq!(entries[0].code,"workload_deploy.initiated");assert_eq!(entries[0].summary,"Managed workload deployment initiated.");assert_eq!(entries[0].detail,None);assert_eq!(entries[0].entity_id,None);assert_eq!(entries[0].entity_name,None);let raw=fs::read_to_string(dir.path().join("activity.json")).unwrap();for secret in [operation.transient_unit_id.as_deref().unwrap(),"systemd-run","/usr/local","FAKE_STDERR_SECRET","FAKE_SECRET_VALUE"]{assert!(!raw.contains(secret),"activity exposed {secret}");}assert!(!dir.path().join("administration.json").exists());operation=result;let replay=Script{replies:Mutex::new(VecDeque::from(vec![running()])),commands:Mutex::new(vec![])};reconcile_detached_workload_with(dir.path(),&operation,&replay).unwrap();assert_eq!(activities(dir.path()).len(),1);}

#[test]
fn uncertain_dispatch_waits_for_known_active_unit_then_emits_once(){let(dir,operation,script)=setup(ManagedWorkloadOperationState::DispatchPrepared,ManagedWorkloadDispatchState::NotAttempted,vec![Err(SshError::ConnectionTimeout)]);let target=TargetRevision::parse(&operation.target_revision).unwrap();let command=fixed_detached_dispatch_command(operation.transient_unit_id.as_deref().unwrap(),&operation.action_id,&target,"deploy").unwrap();let uncertain=dispatch_prepared_with(dir.path(),DispatchPrepared{operation,command,target:SshTarget{host:"host.example".into(),port:22,username:"deploy".into()}},&script).unwrap();assert_eq!(uncertain.state,ManagedWorkloadOperationState::DispatchUncertain);assert!(activities(dir.path()).is_empty());let observer=Script{replies:Mutex::new(VecDeque::from(vec![running()])),commands:Mutex::new(vec![])};let deploying=reconcile_detached_workload_with(dir.path(),&uncertain,&observer).unwrap();assert_eq!(deploying.state,ManagedWorkloadOperationState::Deploying);assert!(deploying.initiated_activity_emitted);assert_eq!(activities(dir.path()).len(),1);let reloaded=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();let replay=Script{replies:Mutex::new(VecDeque::from(vec![running()])),commands:Mutex::new(vec![])};reconcile_detached_workload_with(dir.path(),&reloaded,&replay).unwrap();assert_eq!(activities(dir.path()).len(),1);}

#[test]
fn terminal_failure_emits_once_and_success_only_awaits_verification(){let(dir,operation,script)=setup(ManagedWorkloadOperationState::Deploying,ManagedWorkloadDispatchState::Accepted,vec![ok("LoadState=loaded\nActiveState=failed\nSubState=failed\n")]);let failed=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(failed.state,ManagedWorkloadOperationState::DeploymentFailed);assert!(failed.failure_activity_emitted);assert_eq!(activities(dir.path()).iter().map(|a|a.code.as_str()).collect::<Vec<_>>(),vec!["workload_deploy.failed"]);let reloaded=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(reconcile_detached_workload_with(dir.path(),&reloaded,&Script{replies:Mutex::new(VecDeque::new()),commands:Mutex::new(vec![])}),Err(PrepareError::Internal));assert_eq!(activities(dir.path()).len(),1);let(dir,operation,script)=setup(ManagedWorkloadOperationState::Deploying,ManagedWorkloadDispatchState::Accepted,vec![ok("LoadState=loaded\nActiveState=active\nSubState=exited\nResult=success\nExecMainCode=exited\nExecMainStatus=0\n")]);let success=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(success.state,ManagedWorkloadOperationState::AwaitingVerification);assert!(activities(dir.path()).is_empty());assert!(!dir.path().join("administration.json").exists());}
