use super::*;
use crate::{domain::{device::{Device,DeviceType},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState}},infrastructure::ssh::{RemoteExecutionResult,SshError},storage::{device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_operation_repository::JsonManagedWorkloadOperationRepository}};
use std::{collections::VecDeque,fs,sync::Mutex,time::Duration};
struct Script{replies:Mutex<VecDeque<Result<RemoteExecutionResult,SshError>>>,commands:Mutex<Vec<String>>}
impl RemoteExecutor for Script{fn execute(&self,_:&SshTarget,command:&str,_:Duration)->Result<RemoteExecutionResult,SshError>{self.commands.lock().unwrap().push(command.into());self.replies.lock().unwrap().pop_front().expect("script reply")}}
fn ok(stdout:&str)->Result<RemoteExecutionResult,SshError>{Ok(RemoteExecutionResult{exit_code:Some(0),stdout:stdout.into(),stderr:"FAKE_STDERR_SECRET".into(),duration_ms:1,timed_out:false})}
fn setup(state:ManagedWorkloadOperationState,deadline:&str,replies:Vec<Result<RemoteExecutionResult,SshError>>)->(tempfile::TempDir,ManagedWorkloadOperation,Script){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services:vec![],created_at:"x".into(),updated_at:"x".into()};JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();let dispatch_state=if state==ManagedWorkloadOperationState::DispatchUncertain{ManagedWorkloadDispatchState::Uncertain}else{ManagedWorkloadDispatchState::Accepted};let operation=ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:1,trusted_action_digest:"a".repeat(64),target_revision:"b".repeat(40),deployment_fingerprint:"c".repeat(64),transient_unit_id:Some(format!("pihub-workload-{}.service","d".repeat(32))),dispatch_state,state,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:Some(deadline.into()),completed_at:None,failure:None};JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();(dir,operation,Script{replies:Mutex::new(VecDeque::from(replies)),commands:Mutex::new(vec![])})}
fn assert_status_only(script:&Script,unit:&str){let commands=script.commands.lock().unwrap();assert_eq!(commands.len(),1);assert_eq!(commands[0],format!("sudo -n systemctl show --property=LoadState --property=ActiveState --property=SubState --property=Result --property=ExecMainCode --property=ExecMainStatus --property=ExecMainStartTimestampMonotonic --property=ExecMainExitTimestampMonotonic -- {unit}"));assert!(!commands[0].contains("systemd-run")&&!commands[0].contains(" apply"));}
#[test]
fn active_units_promote_accepted_and_uncertain_operations_to_deploying(){for state in [ManagedWorkloadOperationState::Deploying,ManagedWorkloadOperationState::DispatchUncertain]{let(dir,operation,script)=setup(state,"2099-01-01T00:00:00Z",vec![ok("LoadState=loaded\nActiveState=active\nSubState=running\n")]);let result=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(result.state,ManagedWorkloadOperationState::Deploying);assert_eq!(result.dispatch_state,ManagedWorkloadDispatchState::Accepted);assert_status_only(&script,result.transient_unit_id.as_deref().unwrap());}}
#[test]
fn terminal_success_waits_for_verification_with_both_supported_exec_main_codes(){for code in ["exited","1"]{let(dir,operation,script)=setup(ManagedWorkloadOperationState::Deploying,"2099-01-01T00:00:00Z",vec![ok(&format!("LoadState=loaded\nActiveState=active\nSubState=exited\nResult=success\nExecMainCode={code}\nExecMainStatus=0\n"))]);let result=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(result.state,ManagedWorkloadOperationState::AwaitingVerification);assert!(!result.requires_recovery());assert_status_only(&script,result.transient_unit_id.as_deref().unwrap());}}
#[test]
fn failed_or_unresolved_units_never_redispatch(){let(dir,operation,script)=setup(ManagedWorkloadOperationState::Deploying,"2099-01-01T00:00:00Z",vec![ok("LoadState=loaded\nActiveState=failed\nSubState=failed\n")]);let failed=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(failed.state,ManagedWorkloadOperationState::DeploymentFailed);assert!(!failed.requires_recovery());assert_status_only(&script,failed.transient_unit_id.as_deref().unwrap());let(dir,operation,script)=setup(ManagedWorkloadOperationState::DispatchUncertain,"2099-01-01T00:00:00Z",vec![ok("LoadState=not-found\n")]);let unresolved=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(unresolved.state,ManagedWorkloadOperationState::DispatchUncertain);assert!(unresolved.requires_recovery());assert_status_only(&script,unresolved.transient_unit_id.as_deref().unwrap());}
#[test]
fn transport_failure_preserves_recovery_and_raw_observation_is_discarded(){let(dir,operation,script)=setup(ManagedWorkloadOperationState::Deploying,"2099-01-01T00:00:00Z",vec![Err(SshError::ConnectionTimeout)]);let result=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(result,operation);assert!(result.requires_recovery());assert_status_only(&script,result.transient_unit_id.as_deref().unwrap());let raw=fs::read_to_string(dir.path().join("managed-workload-operations.json")).unwrap();for value in ["systemctl","FAKE_STDERR_SECRET","stdout","stderr","/usr/local","FAKE_SECRET_VALUE"]{assert!(!raw.contains(value),"persisted {value}");}}
#[test]
fn expired_observation_never_kills_or_redispatches_and_manual_recheck_uses_same_unit(){let(dir,operation,script)=setup(ManagedWorkloadOperationState::Deploying,"2000-01-01T00:00:00Z",vec![]);let expired=reconcile_detached_workload_with(dir.path(),&operation,&script).unwrap();assert_eq!(expired.state,ManagedWorkloadOperationState::StillRunning);assert_eq!(expired.transient_unit_id,operation.transient_unit_id);assert!(script.commands.lock().unwrap().is_empty());let later=Script{replies:Mutex::new(VecDeque::from(vec![ok("LoadState=loaded\nActiveState=active\nSubState=running\n")])),commands:Mutex::new(vec![])};let result=reconcile_detached_workload_with(dir.path(),&expired,&later).unwrap();assert_eq!(result.transient_unit_id,operation.transient_unit_id);assert_eq!(result.state,ManagedWorkloadOperationState::Deploying);assert_status_only(&later,result.transient_unit_id.as_deref().unwrap());}
#[test]
fn reload_preserves_identity_and_terminal_states_do_not_recover(){for state in [ManagedWorkloadOperationState::Deploying,ManagedWorkloadOperationState::DispatchUncertain]{let(dir,operation,script)=setup(state,"2099-01-01T00:00:00Z",vec![ok("LoadState=loaded\nActiveState=active\nSubState=running\n")]);let reloaded=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(reloaded.id,operation.id);assert_eq!(reloaded.transient_unit_id,operation.transient_unit_id);assert_eq!(reloaded.observation_deadline,operation.observation_deadline);let result=reconcile_detached_workload_with(dir.path(),&reloaded,&script).unwrap();assert_eq!(result.id,operation.id);}for state in [ManagedWorkloadOperationState::AwaitingVerification,ManagedWorkloadOperationState::DeploymentFailed]{let(dir,operation,script)=setup(state,"2099-01-01T00:00:00Z",vec![ok("LoadState=loaded\nActiveState=active\nSubState=running\n")]);assert!(!operation.requires_recovery());assert_eq!(reconcile_detached_workload_with(dir.path(),&operation,&script),Err(PrepareError::Internal));assert!(script.commands.lock().unwrap().is_empty());}}
