use super::*;
use crate::{domain::{device::{Device,DeviceType},managed_workload::{ManagedWorkload,ManagedWorkloadFile},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState}},infrastructure::ssh::{RemoteExecutionResult,SshError},storage::{device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_repository::{ManagedWorkloadRepository,JsonManagedWorkloadRepository},managed_workload_operation_repository::JsonManagedWorkloadOperationRepository}};
use std::{collections::VecDeque,fs,path::PathBuf,sync::Mutex,time::Duration};
struct Script{replies:Mutex<VecDeque<Result<RemoteExecutionResult,SshError>>>,commands:Mutex<Vec<String>>,storage:PathBuf}
impl RemoteExecutor for Script{fn execute(&self,_:&SshTarget,command:&str,_:Duration)->Result<RemoteExecutionResult,SshError>{if command.contains("systemd-run"){let operation=JsonManagedWorkloadOperationRepository::new(&self.storage).get("pi5","finance").expect("persisted attempt boundary");assert_eq!(operation.state,ManagedWorkloadOperationState::Dispatching);assert_eq!(operation.dispatch_state,ManagedWorkloadDispatchState::Attempted);assert!(operation.transient_unit_id.is_some()&&operation.observation_deadline.is_some());}self.commands.lock().unwrap().push(command.into());self.replies.lock().unwrap().pop_front().expect("script reply")}}
fn ok(stdout:String)->Result<RemoteExecutionResult,SshError>{Ok(RemoteExecutionResult{exit_code:Some(0),stdout,stderr:"FAKE_STDERR_SECRET".into(),duration_ms:1,timed_out:false})}
fn setup(dispatch:Result<RemoteExecutionResult,SshError>)->(tempfile::TempDir,ManagedWorkloadOperation,Script){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services:vec![],created_at:"x".into(),updated_at:"x".into()};let workload=ManagedWorkload{id:"finance".into(),device_id:"pi5".into(),name:"Finance".into(),action_id:"personal-finance".into(),compose_project:Some("finance".into()),required_compose_services:vec!["app".into()],required_service_health_ids:vec![],enabled:true,config_revision:1};JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();JsonManagedWorkloadRepository::new(dir.path()).save(&ManagedWorkloadFile{schema_version:1,workloads:vec![workload.clone()]}).unwrap();let target=TargetRevision::parse(&"c".repeat(40)).unwrap();let operation=ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:1,trusted_action_digest:"b".repeat(64),target_revision:target.as_str().into(),deployment_fingerprint:fingerprint(&workload.id,1,&"b".repeat(64),&target,&verification(&workload)).0,transient_unit_id:None,dispatch_state:ManagedWorkloadDispatchState::NotAttempted,state:ManagedWorkloadOperationState::Prepared,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:None,completed_at:None,failure:None};let script=Script{replies:Mutex::new(VecDeque::from(vec![ok(format!("PIHUB_M17_TRUST=trusted\nPIHUB_M17_ACTION_DIGEST={}\n","b".repeat(64))),ok(format!(r#"{{"protocolVersion":1,"status":"ready","currentRevision":"{}","targetRevision":"{}","changeCount":1}}"#,"a".repeat(40),target.as_str())),dispatch])),commands:Mutex::new(vec![]),storage:dir.path().into()};(dir,operation,script)}
fn dispatch(dir:&std::path::Path,operation:&ManagedWorkloadOperation,script:&Script)->(DispatchPrepared,ManagedWorkloadOperation){let eligible=match revalidate_dispatch_consent_with(dir,operation,script,&DeviceMaintenanceCoordinator::new()).unwrap(){DispatchConsent::DispatchEligible(value)=>value,DispatchConsent::PlanChanged=>panic!("unexpected plan drift")};let prepared=prepare_detached_dispatch(dir,eligible).unwrap();let result=dispatch_prepared_with(dir,prepared.clone(),script).unwrap();(prepared,result)}
fn assert_persisted(dir:&std::path::Path,operation:&ManagedWorkloadOperation){assert_eq!(JsonManagedWorkloadOperationRepository::new(dir).get("pi5","finance"),Some(operation.clone()));}
#[test]
fn confirmed_acceptance_dispatches_once_and_persists_same_unit_for_observation(){let(dir,operation,script)=setup(ok(String::new()));let(prepared,result)=dispatch(dir.path(),&operation,&script);assert_eq!(script.commands.lock().unwrap().len(),3);assert_eq!(result.state,ManagedWorkloadOperationState::Deploying);assert_eq!(result.dispatch_state,ManagedWorkloadDispatchState::Accepted);assert_eq!(result.transient_unit_id,prepared.operation.transient_unit_id);assert_eq!(result.observation_deadline,prepared.operation.observation_deadline);assert_persisted(dir.path(),&result);}
#[test]
fn post_attempt_failures_are_uncertain_without_retry_and_preserve_unit(){for failure in [SshError::ConnectionRefused,SshError::RemoteCommandTimeout,SshError::OutputLimitExceeded]{let(dir,operation,script)=setup(Err(failure));let(prepared,result)=dispatch(dir.path(),&operation,&script);assert_eq!(script.commands.lock().unwrap().len(),3);assert_eq!(result.state,ManagedWorkloadOperationState::DispatchUncertain);assert_eq!(result.dispatch_state,ManagedWorkloadDispatchState::Uncertain);assert_eq!(result.transient_unit_id,prepared.operation.transient_unit_id);assert_eq!(result.observation_deadline,prepared.operation.observation_deadline);assert_persisted(dir.path(),&result);}}
#[test]
fn pre_executor_persistence_mismatch_remains_not_attempted_and_makes_zero_calls(){let(dir,operation,script)=setup(ok(String::new()));let eligible=match revalidate_dispatch_consent_with(dir.path(),&operation,&script,&DeviceMaintenanceCoordinator::new()).unwrap(){DispatchConsent::DispatchEligible(value)=>value,DispatchConsent::PlanChanged=>panic!("unexpected plan drift")};let mut prepared=prepare_detached_dispatch(dir.path(),eligible).unwrap();let original=prepared.operation.clone();prepared.operation.state=ManagedWorkloadOperationState::Prepared;assert_eq!(dispatch_prepared_with(dir.path(),prepared,&script),Err(PrepareError::PersistenceFailed));assert_eq!(script.commands.lock().unwrap().len(),2);assert_eq!(JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance"),Some(original));}
#[test]
fn accepted_and_uncertain_reloads_preserve_deadline_unit_and_exclude_remote_data(){for dispatch_reply in [ok(String::new()),Err(SshError::ConnectionTimeout)]{let(dir,operation,script)=setup(dispatch_reply);let(_,result)=dispatch(dir.path(),&operation,&script);let reloaded=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(reloaded.transient_unit_id,result.transient_unit_id);assert_eq!(reloaded.observation_deadline,result.observation_deadline);let raw=fs::read_to_string(dir.path().join("managed-workload-operations.json")).unwrap();for value in ["systemd-run","/usr/local","FAKE_STDERR_SECRET","FAKE_ENV=present","FAKE_SECRET_VALUE","stdout","stderr"]{assert!(!raw.contains(value),"persisted {value}");}}}
