use super::*;
use crate::{domain::{activity::ActivityEvent,device::{Device,DeviceService,DeviceType},managed_workload::{ManagedWorkload,ManagedWorkloadFile},managed_workload_operation::{ManagedWorkloadDispatchState,ManagedWorkloadOperationState},service_health::{ServiceCheckResult,ServiceFailureReason}},storage::{activity_repository::{ActivityRepository,JsonActivityRepository},device_repository::{DeviceRepository,JsonDeviceRepository},managed_workload_operation_repository::JsonManagedWorkloadOperationRepository,managed_workload_repository::{JsonManagedWorkloadRepository,ManagedWorkloadRepository}}};
use std::{cell::Cell,collections::VecDeque,fs,rc::Rc,time::{Duration,Instant}};
fn service(id:&str)->DeviceService{DeviceService{id:id.into(),name:"Registered".into(),url:"https://secret-token.example.test/health".into(),icon:None,description:None,enabled:true,container_name:None}}
fn operation()->ManagedWorkloadOperation{ManagedWorkloadOperation{schema_version:1,id:"operation-1".into(),device_id:"pi5".into(),workload_id:"finance".into(),action_id:"personal-finance".into(),config_revision:1,trusted_action_digest:"a".repeat(64),target_revision:"b".repeat(40),deployment_fingerprint:"c".repeat(64),transient_unit_id:Some(format!("pihub-workload-{}.service","d".repeat(32))),dispatch_state:ManagedWorkloadDispatchState::Accepted,state:ManagedWorkloadOperationState::WorkloadRuntimeVerified,created_at:"x".into(),prepared_at:Some("x".into()),started_at:None,observation_deadline:Some("2099-01-01T00:00:00Z".into()),completed_at:None,failure:None,initiated_activity_emitted:true,failure_activity_emitted:false,completion_activity_emitted:false}}
fn setup(required:&[&str],services:Vec<DeviceService>)->(tempfile::TempDir,ManagedWorkloadOperation){let dir=tempfile::tempdir().unwrap();let device=Device{id:"pi5".into(),name:"pi".into(),host:"host.example".into(),ssh_port:22,ssh_username:"deploy".into(),description:None,device_type:DeviceType::RaspberryPi,monitoring_enabled:true,refresh_interval_seconds:None,notify_on_device_offline:true,notify_on_container_failure:true,notify_on_container_unhealthy:true,services,created_at:"x".into(),updated_at:"x".into()};let workload=ManagedWorkload{id:"finance".into(),device_id:"pi5".into(),name:"Finance".into(),action_id:"personal-finance".into(),compose_project:Some("finance".into()),required_compose_services:vec!["app".into()],required_service_health_ids:required.iter().map(|id|(*id).into()).collect(),enabled:true,config_revision:1};let operation=operation();JsonDeviceRepository::new(dir.path()).save_all(&[device]).unwrap();JsonManagedWorkloadRepository::new(dir.path()).save(&ManagedWorkloadFile{schema_version:1,workloads:vec![workload]}).unwrap();JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();(dir,operation)}
fn activity(dir:&std::path::Path)->Vec<ActivityEvent>{JsonActivityRepository::new(dir).load_all()}
fn run(dir:&std::path::Path,operation:&ManagedWorkloadOperation,replies:Vec<ServiceCheckResult>,advance:Duration)->Result<ManagedWorkloadOperation,FinalVerificationError>{let mut replies=VecDeque::from(replies);let start=Instant::now();let elapsed=Rc::new(Cell::new(Duration::ZERO));let current=elapsed.clone();let waited=elapsed.clone();let mut check=move|_:&DeviceService|replies.pop_front().expect("health reply");let mut now=move||start+current.get();let mut wait=move|_:Duration|waited.set(waited.get()+advance);finalize_workload_verification_with(dir,operation,&mut check,&mut now,&mut wait)}
fn ok()->ServiceCheckResult{ServiceCheckResult::success(204,1)}
fn failed()->ServiceCheckResult{ServiceCheckResult::failure(Some(503),Some(1),ServiceFailureReason::HttpStatus)}

#[test]
fn runtime_verified_services_must_all_freshly_pass_before_completed(){let(dir,operation)=setup(&["one","two"],vec![service("one"),service("two")]);let completed=run(dir.path(),&operation,vec![ok(),ok()],Duration::from_secs(1)).unwrap();assert_eq!(completed.state,ManagedWorkloadOperationState::Completed);assert!(completed.completed_at.is_some());assert!(completed.completion_activity_emitted);assert!(!completed.failure_activity_emitted);let events=activity(dir.path());assert_eq!(events.iter().map(|item|item.code.as_str()).collect::<Vec<_>>(),vec!["workload.deployment.completed"]);assert!(events[0].detail.is_none()&&events[0].entity_id.is_none());let reloaded=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(run(dir.path(),&reloaded,vec![],Duration::ZERO),Err(FinalVerificationError::InvalidLifecycle));assert_eq!(activity(dir.path()).len(),1);}

#[test]
fn temporary_failure_retries_within_window_but_expiry_becomes_terminal_failure(){let(dir,operation)=setup(&["one"],vec![service("one")]);let completed=run(dir.path(),&operation,vec![failed(),ok()],Duration::from_secs(1)).unwrap();assert_eq!(completed.state,ManagedWorkloadOperationState::Completed);let(dir,operation)=setup(&["one"],vec![service("one")]);assert_eq!(run(dir.path(),&operation,vec![failed(),failed()],Duration::from_secs(120)),Err(FinalVerificationError::ServiceFailed));let failed_operation=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(failed_operation.state,ManagedWorkloadOperationState::VerificationFailed);assert_eq!(failed_operation.failure,Some(ManagedWorkloadFailure::VerificationServiceFailed));assert!(failed_operation.failure_activity_emitted);assert!(!failed_operation.completion_activity_emitted);assert!(!failed_operation.requires_recovery());assert_eq!(activity(dir.path()).iter().map(|item|item.code.as_str()).collect::<Vec<_>>(),vec!["workload_deploy.failed"]);assert_eq!(run(dir.path(),&failed_operation,vec![],Duration::ZERO),Err(FinalVerificationError::InvalidLifecycle));assert_eq!(activity(dir.path()).len(),1);}

#[test]
fn fresh_http_transport_and_timeout_failures_never_use_cached_health(){for reason in [ServiceFailureReason::HttpStatus,ServiceFailureReason::Connection,ServiceFailureReason::Timeout]{let(dir,operation)=setup(&["one"],vec![service("one")]);let failed=ServiceCheckResult::failure(None,None,reason);assert_eq!(run(dir.path(),&operation,vec![failed.clone(),failed],Duration::from_secs(120)),Err(FinalVerificationError::ServiceFailed));let saved=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(saved.state,ManagedWorkloadOperationState::VerificationFailed);assert_eq!(saved.failure,Some(ManagedWorkloadFailure::VerificationServiceFailed));assert_eq!(activity(dir.path()).iter().filter(|event|event.code=="workload_deploy.failed").count(),1);}}

#[test]
fn missing_health_target_and_wrong_lifecycle_fail_closed_without_cached_health(){let(dir,operation)=setup(&["missing"],vec![service("other")]);assert_eq!(run(dir.path(),&operation,vec![],Duration::ZERO),Err(FinalVerificationError::ServiceMissing));let failed_operation=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(failed_operation.failure,Some(ManagedWorkloadFailure::VerificationServiceMissing));assert_eq!(activity(dir.path()).len(),1);let(dir,mut operation)=setup(&["one"],vec![service("one")]);operation.state=ManagedWorkloadOperationState::RevisionVerified;JsonManagedWorkloadOperationRepository::new(dir.path()).save(&operation).unwrap();assert_eq!(run(dir.path(),&operation,vec![ok()],Duration::ZERO),Err(FinalVerificationError::InvalidLifecycle));assert!(activity(dir.path()).is_empty());}

#[test]
fn empty_service_list_uses_runtime_gate_but_invalid_independent_targets_fail_closed_and_never_leak(){let(dir,operation)=setup(&[],vec![]);let completed=run(dir.path(),&operation,vec![],Duration::ZERO).unwrap();assert_eq!(completed.state,ManagedWorkloadOperationState::Completed);let(dir,operation)=setup(&[],vec![]);let raw=r#"{"schemaVersion":1,"workloads":[{"id":"finance","deviceId":"pi5","name":"Finance","actionId":"personal-finance","composeProject":null,"requiredComposeServices":[],"requiredServiceHealthIds":[],"enabled":true,"configRevision":1}]}"#;fs::write(dir.path().join("managed-workloads.json"),raw).unwrap();assert_eq!(run(dir.path(),&operation,vec![],Duration::ZERO),Err(FinalVerificationError::WorkloadUnavailable));let failed_operation=JsonManagedWorkloadOperationRepository::new(dir.path()).get("pi5","finance").unwrap();assert_eq!(failed_operation.state,ManagedWorkloadOperationState::VerificationFailed);let stored=fs::read_to_string(dir.path().join("managed-workload-operations.json")).unwrap();let events=fs::read_to_string(dir.path().join("activity.json")).unwrap();for secret in ["secret-token","https://","FAKE_HTTP_BODY","systemd-run"," apply","docker compose","/usr/local"]{assert!(!stored.contains(secret)&&!events.contains(secret),"persisted {secret}");}}
